ModLanguage('EN', {
  "REPLACE ALL": {
    "Cursor": "Hand",
    "Grandma": "Steve",
    "grandmas": "Steves",
    "Grandma’s": "Steve’s",
    "Anti-grandma": "Herobrine",
    "one (feminine)": "one (masculine)",
    "Grandmothers": "Steves",
    "grandmothers (genitive)": "of Steves",
    "grandmother": "Steve",
    "To Grandma": "To Steve",
    "grandma": "Steve",
    "Of grandmas": "Of Steves",
    "grandmas (plural)": "Steves",
    "Grandma (accusative)": "Steve (accusative)",
    "Grandmas": "Steves",
    "by grandma": "by Steve",
    "Grandma’s (possessive)": "Steve’s",
    "Good (feminine)": "Good (masculine)",
    "Baked (feminine)": "baked (masculine)",
    "Factory": "Furnace",
    "mines": "shafts",
    "factories": "furnaces",
    "Factories": "Furnaces",
    "Bank": "Emerald",
    "Banks": "Emeralds",
    "bank": "emerald",
    "banks": "emeralds",
    "Of Banks": "Of Emeralds",
    "Temple": "Storage",
    "Temples (genitive)": "Storages",
    "Temples": "Storages",
    "wizard towers": "pillager outposts",
    "Wizard Tower": "Pillager Outpost",
    "Wizard Towers (genitive)": "Pillager Outposts",
    "wizard towers (plural)": "pillager outposts",
    "Alchemy Lab": "Brewing Stand",
    "alchemy lab": "brewing stand",
    "Alchemy Labs": "Brewing Stands",
    "alchemy labs": "brewing stands",
    "Antimatter Condenser": "Redstone",
    "antimatter condenser": "redstone",
    "antimatter condensers": "redstones",
    "of antimatter condensers": "of redstone",
    "Cookie Universe": "Nether",
    "Prism": "Beacon",
    "prism": "beacon",
    "prisms": "beacons",
    "of prisms": "of beacons",
    "Chancemaker": "Enchantment Table",
    "chancemaker": "enchantment table",
    "chancemakers": "enchantment tables",
    "of chancemakers": "of enchantment tables",
    "clovers": "enchantment tables",
    "Empty Universe": "End Portal",
    "dead universes": "End Portals",
    "empty universe": "end portal",
    "empty universes": "end portals",
    "of empty universes": "of end portals",
    "Fractal Engine": "Anvil",
    "fractal engine": "anvil",
    "fractal engines": "anvils",
    "of fractal engines": "of anvils",
    "Javascript Console": "Command Block",
    "javascript consoles": "command blocks",
    "console Javascript": "command block",
    "consoles Javascript": "command blocks",
    "Of Javascript Consoles": "Of Command Blocks",
    "Cork Baker": "Iron Golem",
    "cork baker": "iron golem",
    "cork bakers": "iron golems",
    "wrinkler (genitive)": "mob (genitive)",
    "wrinkler": "mob",
    "Wrinkler": "Mob",
    "of wrinklers": "of mobs",
    "Wrinklers": "Mobs",
    "Broken": "Destroyed",
  },
});
